name: Deploy to Github Pages

on:
  push:
    branches: ["main"]
  # release:
  #   types: [created]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  node-version: 16

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js version ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn run check
      - run: yarn run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js version ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn run build --base=/${{ github.event.repository.name }}/
      - run: cp ./dist/index.html ./dist/404.html 

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
